### ISSUE TITLE
Freezing of script when initializing aedat class in python 

### ISSUE THREAD

**Issue by PMMon** [norse/aedat#8] opened 2021-04-15 13:51 UTC
When running the simple examples in python suggested on the ReadMe page, the script freezes and it is not possible to cancel it anymore (have to close the terminal, as even crtl+c won't work).
After some investigation this seems to appear when a class such as `aedat.AEDAT` is initialized e.g. in: 

`data = aedat.AEDAT("example_data/ibm/user01_natural.aedat")`

**Comment by cpehle** [comment] 2021-04-15 17:45
I was unable to reproduce the problem on my computer, could you give me some more details on which system you are running on, what pytorch version, etc. you are using?

**Comment by cpehle** [comment] 2021-04-15 17:46
Perhaps an important point is that the initialisation already loads the data, so this might just be a symptom of a slow hard drive / cpu.

**Comment by PMMon** [comment] 2021-04-21 13:46
Running on Ubuntu 20.04, pytorch version 1.81. It appears that the data (in this case _example_data/ibm/user01_natural.aedat_) is being parsed quite extensively, as it runs the following loop for more than half an hour (stopped the script after that time):

```
  do {
    std::cout << "Parsing data until end is found" << std::endl << std::flush;
    fs.getline(line, 128);
    str = std::string(line);
  } while (str.rfind("#!END-HEADER", 0) != 0);
```
This loop is part of the function `void load(const std::string &filename)`. This might maybe be a problem related to the dataset?

**Comment by cpehle** [comment] 2021-04-21 22:50
I think the issue is that the example data is stored via git-lfs, the data loader assumes that the input is valid and a ```git clone``` only creates a "placeholder file" for data stored via git-lfs. Installation instructions for git-lfs can be found here https://git-lfs.github.com, once installed you should be able to fetch the example data by running ```git lfs fetch```. I probably should update the README.md to include this information.

**Comment by cpehle** [comment] 2021-04-27 18:53
I will close this issue for now, if downloading the files using git-lfs doesn't solve the issue, feel free to reopen.

**Closed by cpehle** 2021-04-27 18:53 UTC
Labels: performance
